version: '3.8'

services:
  token-tracker-db:
    image: "postgres"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: token-tracker
    ports:
      - "5434:5432"
    volumes:
      - "token-tracker-data:/var/lib/postgresql/data/"
  token-tracker-testing-db:
    image: "postgres"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: token-tracker-test
    ports:
      - "5435:5432"
    volumes:
      - "token-tracker-test-data:/var/lib/postgresql/data/"

volumes:
  token-tracker-data:
  token-tracker-test-data: